[package]
name = "fodder-macro"
version = "0.1.0"
authors = ["dullbananas"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
fodder-utils = { path = "../fodder-utils", version = "0.1" }
proc-macro2 = "1.0"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
